import "@/assets/styles/main.scss";

import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import { Wrapper } from "@/components";

export const metadata: Metadata = {
  title: {
    default: "NextJS 14 Tutorial",
    template: "%s | NextJS 14",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
